language: erlang
otp_release:
    - 20.2.2
before_script:
    - "chmod +x bootstrap_travis.sh"
    - "./bootstrap_travis.sh"
script:
<<<<<<< HEAD
    - "rm ./config/config_socks5_test.config"
    - "mv ./config/config_socks5_travis.config ./config/config_socks5_test.config"
=======
    - "rm config/config_socks5_test.config"
    - "mv config/config_socks5_travis.config config/config_socks5_test.config"
>>>>>>> origin/master
    - "./rebar3 ct"