language: erlang
otp_release:
    - 20.2.2
before_script:
    - "chmod +x bootstrap_travis.sh"
    - "./bootstrap_travis.sh"
script:
    - "rm ./config/erlang_socks5_test.config"
    - "mv ./config/erlang_socks5_travis.config ./config/erlang_socks5_test.config"
    - "./rebar3 ct"